
language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
node_js:
  -"node"
install: npm run restore
script: 
  - npm run build
  - npm run ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  on:
    branch: master
