
language: csharp
mono: none
dotnet: 1.1.1
dist: trusty
node_js:
  -"node"
install: npm run restore
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    local_dir: dist
    target_branch: gh-pages
    email: deploy@travis-ci.org
    name: Deployment Bot